// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8YakKGnGuAJd4Os5e5oBLiKmz7RpGli0',
    appId: '1:1065140481985:web:73df968a4f7274730a8940',
    messagingSenderId: '1065140481985',
    projectId: 'antra-club',
    authDomain: 'antra-club.firebaseapp.com',
    storageBucket: 'antra-club.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCReBv9C0YIEJlEqO_0HYZSZWE6JjnWKK4',
    appId: '1:1065140481985:android:6a6f071b6d6b1e310a8940',
    messagingSenderId: '1065140481985',
    projectId: 'antra-club',
    storageBucket: 'antra-club.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwweQjvhweFGCevOcAd7RxyfX5QEAt7Zs',
    appId: '1:1065140481985:ios:1844d2e5a84b62d50a8940',
    messagingSenderId: '1065140481985',
    projectId: 'antra-club',
    storageBucket: 'antra-club.appspot.com',
    iosClientId: '1065140481985-odbjum4k1qjtu9iahfvbgq0nl1sd050p.apps.googleusercontent.com',
    iosBundleId: 'club.antra.antra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwweQjvhweFGCevOcAd7RxyfX5QEAt7Zs',
    appId: '1:1065140481985:ios:1844d2e5a84b62d50a8940',
    messagingSenderId: '1065140481985',
    projectId: 'antra-club',
    storageBucket: 'antra-club.appspot.com',
    iosClientId: '1065140481985-odbjum4k1qjtu9iahfvbgq0nl1sd050p.apps.googleusercontent.com',
    iosBundleId: 'club.antra.antra',
  );
}
